### PR TITLE
Fix ToolCache.find and add 

### LINKED ISSUE #7: Calling `ToolCache.find` fails
**Describe the bug**
Calling `ToolCache.find` or `ToolCache.find'` fails with an error:
```
[error]n.find2Impl is not a function
```

**Expected behavior**
It does not fail with a runtime exception and properly passes the arguments to the @actions/tool-cache library.

### PR DESCRIPTION
**Pull request by colinwahl**
**Description of the change**
* Fixes a typo in the FFI implementation of the `GitHub.Actions.ToolCache.find` and `GitHub.Actions.ToolCache.find` functions
* Adds a test action which runs on commit to a branch (or PR)
  * This will be useful in #5 as a simple test script isn't enough - it needs to actually run the action through a real workflow

This intends to close #7.

### CODE REVIEW

File: src/GitHub/Actions/ToolCache.js [hunk 1]
```diff
@@ -49,9 +49,9 @@ exports.cacheFile4Impl = toolCache.cacheFile;
 
 exports.cacheFile5Impl = toolCache.cacheFile;
 
-exports.find2Impl = toolCache.findImpl;
+exports.find2Impl = toolCache.find;
```
Comment (thomashoneyman) [inline src/GitHub/Actions/ToolCache.js:52]: 😅

**Review by thomashoneyman — APPROVED** [review]

**Comment by thomashoneyman** [comment]
We'll need to update setup-purescript as well once this lands.
